---
phrases: # phrases to be detected in the chat message, case-insensitive
  - op me
regular expressions: # regular expressions to be matched
  - #give me op#i
actions: # when a message matches one of the above...
# options:
# "block": don't let the message be sent
# "send warning": send the player a warning message
# "kick": kick the player from the server with reason specified below
# "ban ip": ban the player's IP from the server with reason specified below
# "ban name": ban the player's name from the server with reason specified below
# "tell console": send a message to console about this
# "tell moderators": send a message to players that have the permission chatblocker.moderate
  - block
  - tell console
  - tell moderators
kick message: you asked for op
ban message: you asked for op
warning message: your message was blocked because you asked for op.
...
