name: WorldList
version: 0.1.0
api: [1.0.0]
main: worldlist\Main
commands:
  worldlist:
    description: View a list of players in a world
    usage: /worldlist [world]
    aliases: [wl]
    permission: worldlist.cmd
permissions:
  worldlist:
    description: Allow using everything in WorldList
    children:
      worldlist.cmd:
        description: Allow using the command /worldlist
        default: true
